version: "3"
services:
  arangodb:
    image: arangodb/arangodb:3.7.5
    environment:
      - ARANGO_ROOT_PASSWORD=P69ass
    ports:
      - 8529:8529
  fiberweb:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8800:8800
